name: "dbian-dev"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 0.0.0.0:3000:3000
    container_name: dbian-dev
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./articles:/app/articles
      - ./public:/app/public/
